# pre-commit install
# pre-commit run --all-files
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autoupdate_commit_msg: "chore(deps): update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"
  autoupdate_schedule: "weekly"
  skip:
    - uv-lock
    - pip-compile
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  # * meta hooks
  - repo: meta
    hooks:
      - id: check-hooks-apply
        stages: [manual]
      - id: check-useless-excludes
        stages: [manual]

  # * sync dependencies
  # - repo: https://github.com/wpk-nist-gov/sync-pre-commit-hooks
  #   rev: v0.2.0
  #   hooks:
  #     - id: sync-pre-commit-deps
  #       args:
  #         - "--requirements=requirements/lock/pre-commit-additional-dependencies.txt"
  #       files: >-
  #         ^\.pre-commit-config\.yaml$|^requirements/lock/pre-commit-additional-dependencies\.txt$
  #     - id: sync-uv-dependency-groups
  #     - id: justfile-format
  #       additional_dependencies:
  #         - rust-just==1.45.0

  # * Top level
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        exclude: ^uv[.]lock
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  # * pyproject.toml
  # ** format
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.11.1
    hooks:
      - id: pyproject-fmt
        args: [--indent=4, --keep-full-version]
        files: ""
        types: [toml]
  # ** validate
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
  # ** validate (schema-store)
  - repo: https://github.com/henryiii/validate-pyproject-schema-store
    rev: 2025.11.21
    hooks:
      - id: validate-pyproject
        name: validate-pyproject-schema-store
        stages: [manual]
  # ** repo review
  - repo: https://github.com/scientific-python/cookie
    rev: 2025.11.21
    hooks:
      - id: sp-repo-review
        stages: [manual]

  # * Prettier
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.7.4
    hooks:
      - id: prettier
        alias: markdownlint
        stages: [pre-commit, manual]

  # * Markdown
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.20.0
    hooks:
      - id: markdownlint-cli2
        alias: markdownlint
        args: [--style, prettier]
        # language_version: 10.9.0

  # * Linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.9
    hooks:
      - id: ruff-check
        alias: ruff
        args: [--fix, --show-fixes]
      - id: ruff-format
        alias: ruff
  - repo: https://github.com/adamtheturtle/doccmd-pre-commit
    rev: v2025.12.13
    hooks:
      - id: doccmd
        name: "ruff format markdown"
        alias: ruff
        args:
          - "--language"
          - "python"
          - "--no-pad-file"
          - "--command"
          - "ruff format"
        additional_dependencies:
          - ruff==0.14.9

  # * Spelling
  # ** typos
  # Revert to crate-ci/typos if https://github.com/crate-ci/typos/issues/390 is fixed.
  # - repo: https://github.com/crate-ci/typos
  - repo: https://github.com/adhtruong/mirrors-typos
    rev: v1.40.0
    hooks:
      - id: typos
        exclude_types: [jupyter]
        exclude: ^uv[.]lock$|^requirements
  # ** codespell
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        exclude_types: [jupyter]
        exclude: ^uv[.]lock$|^requirements
        stages: [manual]

  # * Dependencies
  # ** pyproject2conda
  - repo: https://github.com/usnistgov/pyproject2conda
    rev: v0.22.1
    hooks:
      - id: pyproject2conda-project
        alias: requirements
  # ** uv
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.17
    hooks:
      - id: uv-lock
        alias: requirements
        args: [--locked]
      - id: pip-compile
        alias: requirements
        entry: python tools/requirements_lock.py
        pass_filenames: true
        files: ^requirements/[^/]*\.txt$
  # ** update additional dependencies in .pre-commit-config.yaml
  - repo: local
    hooks:
      - id: sync-pre-commit-deps
        name: sync-pre-commit-deps
        entry: sync-pre-commit-deps
        language: python
        files: >-
          ^\.pre-commit-config\.yaml$|^requirements/lock/pre-commit-additional-dependencies\.txt$
        pass_filenames: false
        additional_dependencies:
          - "--editable=.[all]"
        args:
          - "--requirements=requirements/lock/pre-commit-additional-dependencies.txt"

  # * Commit message
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.10.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # * Justfile
  - repo: local
    hooks:
      - id: justfile-format
        name: justfile format
        entry: apply-command just --fmt --unstable --justfile
        language: python
        files: \.?[jJ]ustfile$|.*\.just$
        pass_filenames: true
        additional_dependencies:
          - "--editable=."
          - rust-just==1.43.0

  # * Cruft
  - repo: https://github.com/cruft/cruft.git
    rev: 2.16.0
    hooks:
      - id: cruft
        args: [--checkout, main]
        stages: [manual]

  # * Cog
  - repo: local
    hooks:
      - id: cog-readme
        name: cog-readme
        alias: cog
        entry: >
          python tools/cog_runner.py --group=cog --group=optional-dependencies
          --no-dev --no-active -- README.md
        language: python
        pass_filenames: false
        stages: [manual]

  # * Update "rev" in README.md
  - repo: local
    hooks:
      - id: sync-readme-rev-version
        name: sync-readme-rev-version
        description: update rev version in README.md
        entry: python tools/sync_readme_rev_version.py
        language: python
        pass_filenames: false
        files: ^pyproject\.toml|^README\.md

  # * Update pyproject.tool.uv.dependency-groups python-version minimum
  - repo: local
    hooks:
      - id: sync-uv-dependency-groups
        name: sync-uv-dependency-groups
        entry: sync-uv-dependency-groups
        language: python
        files: ^pyproject.toml$|^\.python-version$
        pass_filenames: false
        additional_dependencies:
          - "--editable=.[all]"

  - repo: local
    hooks:
      - id: sync-pre-commit-language-version
        name: sync-pre-commit-language-version
        entry: sync-pre-commit-language-version
        language: python
        args:
          - "--language-version-file=.python-version"
          - "--hook=typecheck"
        files: ^\.python-version$
        pass_filenames: false
        additional_dependencies:
          - "--editable=.[all]"

  - repo: local
    hooks:
      - id: fill-pre-commit-hook-deps
        name: fill-pre-commit-hook-deps
        alias: typecheck
        entry: fill-pre-commit-deps
        language: python
        files: ^pyproject.toml$|^\.pre-commit-config.yaml$|^requirements/lock/uvx-tools\.txt$
        pass_filenames: false
        args:
          - "--hook=typecheck"
          - "--group=typecheck"
          - "--exclude=pylint"
          - "--requirements=requirements/lock/uvx-tools.txt"
          - "--requirements-include=mypy"
          - "--requirements-include=orjson"
          - "--requirements-include=basedpyright"
          - "--requirements-include=ty"
          - "--requirements-include=pyrefly"
        additional_dependencies:
          - "--editable=.[all]"

  - repo: local
    hooks:
      - id: typecheck
        name: typecheck
        entry: python tools/typecheck.py --verbose
        language: python
        args:
          - "--no-uv"
          # - "--checker=mypy"
          # - "--checker=basedpyright"
          # - "--checker=pylint --enable-all-extensions"
          - "--checker=ty"
          - "--checker=pyrefly"
        files: ^(src/|tests/)
        types_or: [python, pyi]
        require_serial: true
        language_version: "3.13"
        stages: [manual]
        additional_dependencies:
          - basedpyright==1.37.2
          - dependency-groups>=1.3.1
          - lastversion>=3.5.8
          - mypy==1.19.1
          - orjson==3.11.5
          - packaging>=25.0
          - pyrefly==0.50.0
          - pytest
          - requirements-parser>=0.13.0
          - ruamel-yaml>=0.18.16
          - tomli; python_version < "3.11"
          - tomlkit>=0.13.3
          - ty==0.0.14
          - typing-extensions; python_version < "3.11"
