# pre-commit install
# pre-commit run --all-files
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autoupdate_commit_msg: "chore(deps): update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"
  autoupdate_schedule: "weekly"
  skip:
    - uv-lock
    - pip-compile
    - typecheck
    # no way to use these on pre-commit-ci
    - check-file-extension
    - sync-pre-commit-deps
    - justfile-format
    - sync-uv-dependency-groups
    - sync-pre-commit-language-version
    - fill-pre-commit-hook-deps

default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  # * meta hooks
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: local
    hooks:
      - id: check-file-extension
        name: check-file-extension
        entry: check-file-extension
        language: python
        require_serial: true
        args:
          - "-e.rej"
          - "-e.bak"
          - "-e.log"
        additional_dependencies:
          - "--editable=."

  # * sync dependencies
  # - repo: https://github.com/wpk-nist-gov/sync-pre-commit-hooks
  #   rev: v0.2.0
  #   hooks:
  #     - id: sync-pre-commit-deps
  #       args:
  #         - "--requirements=requirements/lock/pre-commit-additional-dependencies.txt"
  #       files: >-
  #         ^\.pre-commit-config\.yaml$|^requirements/lock/pre-commit-additional-dependencies\.txt$
  #     - id: sync-uv-dependency-groups
  #     - id: justfile-format
  #       additional_dependencies:
  #         - rust-just==1.45.0

  # * Forbidden files
  - repo: local
    hooks:
      - id: forbidden-files
        name: forbidden files
        entry: Found forbidden file.
        language: fail
        files: \.(rej|bak)$

  # * Top level
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        exclude: ^uv[.]lock
      - id: check-case-conflict
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending

  # * toml/pyproject.toml
  # ** format
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
        # exclude: (^|/)pyproject\.toml$
      - id: taplo-lint
        args: ["--no-schema"]
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.15.3
    hooks:
      - id: pyproject-fmt
  # ** validate (schema-store)
  - repo: https://github.com/henryiii/validate-pyproject-schema-store
    rev: 2026.01.22
    hooks:
      - id: validate-pyproject
        name: validate-pyproject-schema-store
        stages: [manual]
  # ** repo review
  - repo: https://github.com/scientific-python/cookie
    rev: 2025.11.21
    hooks:
      - id: sp-repo-review
        stages: [manual]

  # * Prettier
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.1
    hooks:
      - id: prettier
        alias: markdownlint
        stages: [pre-commit, manual]
        args:
          - "--cache"
          - "--cache-location=.prettier_cache/cache"

  # * Markdown
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.20.0
    hooks:
      - id: markdownlint-cli2
        alias: markdownlint
        args: [--style, prettier]
        # language_version: 10.9.0

  # * Linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff-check
        alias: ruff
        args: [--fix, --show-fixes]
      - id: ruff-format
        alias: ruff
  - repo: https://github.com/adamtheturtle/doccmd-pre-commit
    rev: v2026.1.31.3
    hooks:
      - id: doccmd
        name: "ruff format markdown"
        alias: ruff
        args:
          - "--language"
          - "python"
          - "--no-pad-file"
          - "--command"
          - "ruff format"
        additional_dependencies:
          - ruff==0.15.0

  # * Spelling
  # ** typos
  # Revert to crate-ci/typos if https://github.com/crate-ci/typos/issues/390 is fixed.
  # - repo: https://github.com/crate-ci/typos
  - repo: https://github.com/adhtruong/mirrors-typos
    rev: v1.43.4
    hooks:
      - id: typos
        exclude_types: [jupyter]
        exclude: ^uv[.]lock$|^requirements

  # * Dependencies
  # ** pyproject2conda
  - repo: https://github.com/usnistgov/pyproject2conda
    rev: v0.22.1
    hooks:
      - id: pyproject2conda-project
        alias: requirements
        args:
          - "--custom-command=prek run pyproject2conda-project --all-files"
  # ** uv
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.2
    hooks:
      - id: uv-lock
        alias: requirements
        args: [--locked]
      - id: pip-compile
        alias: requirements
        entry: python tools/requirements_lock.py
        pass_filenames: true
        files: ^requirements/[^/]*\.txt$
  # ** update additional dependencies in .pre-commit-config.yaml
  - repo: local
    hooks:
      - id: sync-pre-commit-deps
        name: sync-pre-commit-deps
        entry: sync-pre-commit-deps
        language: python
        files: >-
          ^\.pre-commit-config\.yaml$|^requirements/lock/pre-commit-additional-dependencies\.txt$
        pass_filenames: false
        additional_dependencies:
          - "--editable=.[all]"
        args:
          - "--requirements=requirements/lock/pre-commit-additional-dependencies.txt"

  # * Commit message
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.7
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # * Justfile
  - repo: local
    hooks:
      - id: justfile-format
        name: justfile format
        entry: apply-command just --fmt --unstable --justfile
        language: python
        files: \.?[jJ]ustfile$|.*\.just$
        pass_filenames: true
        additional_dependencies:
          - "--editable=."
          - rust-just==1.43.0

  # * Cog
  - repo: local
    hooks:
      - id: cog-readme
        name: cog-readme
        alias: cog
        entry: >
          python tools/cog_runner.py --group=cog --group=optional-dependencies
          --no-dev --no-active -- README.md
        language: python
        pass_filenames: false
        stages: [manual]

  # * Actions
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.36.1
    hooks:
      - id: check-github-workflows
        alias: actions
        priority: 0
      - id: check-github-actions
        alias: actions
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.10
    hooks:
      - id: actionlint
        alias: actions
        stages: [manual]
        args:
          - "-ignore=SC2129" # ignorable stylistic lint from shellcheck
          - "-ignore=SC2016" # another shellcheck lint: seems to have false positives?
        language: golang # means renovate will also update `additional_dependencies`
        additional_dependencies:
          # actionlint has a shellcheck integration which extracts shell scripts in `run:` steps from GitHub Actions
          # and checks these with shellcheck. This is arguably its most useful feature,
          # but the integration only works if shellcheck is installed
          - "github.com/wasilibs/go-shellcheck/cmd/shellcheck@v0.11.1"
        # see https://github.com/rhysd/actionlint/issues/46
        exclude: ^\.github/actions
        priority: 0
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    # Zizmor version.
    rev: v1.22.0
    hooks:
      # Run the linter.
      - id: zizmor
        alias: actions

  # * Update "rev" in README.md
  - repo: local
    hooks:
      - id: sync-readme-rev-version
        name: sync-readme-rev-version
        description: update rev version in README.md
        entry: python tools/sync_readme_rev_version.py
        language: python
        pass_filenames: false
        files: ^pyproject\.toml|^README\.md

  # * Update pyproject.tool.uv.dependency-groups python-version minimum
  - repo: local
    hooks:
      - id: sync-uv-dependency-groups
        name: sync-uv-dependency-groups
        entry: sync-uv-dependency-groups
        language: python
        files: ^pyproject.toml$|^\.python-version$
        pass_filenames: false
        additional_dependencies:
          - "--editable=.[all]"

  - repo: local
    hooks:
      - id: sync-pre-commit-language-version
        name: sync-pre-commit-language-version
        entry: sync-pre-commit-language-version
        language: python
        args:
          - "--language-version-file=.python-version"
          - "--hook=typecheck"
        files: ^\.python-version$
        pass_filenames: false
        additional_dependencies:
          - "--editable=.[all]"

  - repo: local
    hooks:
      - id: fill-pre-commit-hook-deps
        name: fill-pre-commit-hook-deps
        alias: typecheck
        entry: fill-pre-commit-deps
        language: python
        files: ^pyproject.toml$|^\.pre-commit-config.yaml$|^requirements/lock/uvx-tools\.txt$
        pass_filenames: false
        args:
          - "--hook=typecheck-runner"
          - "--group=type"
          - "--exclude=pylint"
          - "--requirements=requirements/lock/uvx-tools.txt"
          - "--requirements-include=ty"
          - "--requirements-include=pyrefly"
        additional_dependencies:
          - "--editable=.[all]"

  # ** typecheck-runner
  - repo: https://github.com/wpk-nist-gov/typecheck-runner
    rev: v0.1.5
    hooks:
      - id: typecheck-runner
        alias: typecheck
        args:
          - "--no-uv"
          - "-v"
          - "--check=ty"
          - "--check=pyrefly"
        files: ^(src/|tests/)
        language_version: "3.14"
        stages: [manual]
        additional_dependencies:
          - dependency-groups>=1.3.1
          - lastversion>=3.5.8
          - packaging>=25.0
          - pyrefly==0.52.0
          - pytest
          - requirements-parser>=0.13.0
          - ruamel-yaml>=0.18.16
          - tomli; python_version < "3.11"
          - tomlkit>=0.13.3
          - ty==0.0.16
          - typecheck-runner>=0.1.0; python_version > "3.9"
          - typing-extensions; python_version < "3.12"
  - repo: https://github.com/jsh9/markdown-toc-creator
    rev: 0.1.3
    hooks:
      - id: markdown-toc-creator
        files: ^README\.md$
        args:
          - --proactive=False
          - --add-toc-title=False
          - --horizontal-rule-style=prettier
