test:
  imports:
    - pre_commit_hooks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wpk-nist-gov/pre-commit-hooks
  summary: Some useful pre-commit hooks
  description: |
    Some useful pre-commit hooks
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
